name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: native
          - os: macos-latest
            target: native
          - os: macos-14
            target: native
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust (stable)
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Setup just
      uses: extractions/setup-just@v2

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install system dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y pkg-config

    - name: Check
      run: cargo check --all-targets --all-features

    - name: Build
      run: cargo build --all-targets --all-features

    - name: Run full checks (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: just check
